### ISSUE TITLE
How to know if the pagar.me is open or was closed?

### ISSUE THREAD

**Issue by Calzzetta** [pagarme/pagarme-ng-checkout#13]
Hi,

Is there a way to know if the chechout is ready after $pgCheckout.open()?
Should be also good to know if the user closed the popup cancelling the payment flow.

Best regards,
Douglas

**Comment by felquis** [comment]
It is not possible right now, we only have a callback for the `success` event https://docs.pagar.me/checkout/#inserindo-o-checkout-via-api
